app/models/QuestionAnswerForm.php
<?php
namespace app\models;

use app\db\records\QuestionAnswer;
use Yii;
use yii\base\Model;

/**
 * @author Mark Moskalenko <office@it-yes.com>
 */
class QuestionAnswerForm extends Model
{
    use FillableTrait;

    /**
     * @var integer
     */
    public $qaCategoryId;
    /**
     * @var string
     */
    public $title;
    /**
     * @var string
     */
    public $email;
    /**
     * @var string
     */
    public $question;
    /**
     * @var integer
     */
    public $userId;
    /**
     * @var integer
     */
    public $isMailNotification;
    /**
     * @var integer
     */
    public $status;
    /**
     * @var string
     */
    public $firstName;
    /**
     * @var array
     */
    public $photos = [];

    /**
     * @return array
     */
    public function rules()
    {
        return [
            ['qaCategoryId', 'required'],
            ['qaCategoryId', 'integer'],
            ['title', 'required'],
            ['title', 'string', 'max' => 255],
            ['title', 'trim'],
            ['email', 'required', 'when' => function() { return Yii::$app->user->isGuest; }],
            ['email', 'string', 'max' => 255],
            ['email', 'trim'],
            ['email', 'email'],
            ['question', 'required'],
            ['question', 'string'],
            ['question', 'trim'],
            ['userId', 'integer'],
            ['isMailNotification', 'boolean'],
            ['isMailNotification', 'default', 'value'=>1],
            ['status', 'integer'],
            ['status', 'default', 'value' => QuestionAnswer::STATUS_NEW],
            ['status', 'in', 'range' => [QuestionAnswer::STATUS_NEW, QuestionAnswer::STATUS_ANSWERED]],
            ['firstName', 'string', 'max' => 255],
            ['firstName', 'trim'],
            ['photos', 'each', 'rule' => ['integer']],
        ];
    }

    /**
     * @return array
     */
    public function fillable()
    {
        return ['qaCategoryId', 'userId', 'title', 'email', 'firstName', 'question', 'isMailNotification', 'status'];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'qaCategoryId' => 'Категория вопроса',
            'userId' => 'Пользователь',
            'title' => 'Заголовок вопроса',
            'email' => 'Email',
            'firstName' => 'Имя',
            'question' => 'Вопрос',
            'isMailNotification' => 'Сообщать мне об ответах и комментариях на e-mail',
            'status' => 'Статус',
            'timeCreated' => 'Дата создания',
            'timeUpdated' => 'Дата обновления',
            'photos' => 'Фотографии',
        ];
    }
}

app/controllers/QuestionAnswerController.php
<?php
namespace app\controllers;

use app\helpers\Url;
use app\modules\forum\repositories\ThemeRepository;
use app\repositories\QuestionAnswerCategoryRepository;
use app\repositories\QuestionAnswerRepository;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * @author Mark Moskalenko <office@it-yes.com>
 */
class QuestionAnswerController extends BaseController
{
    /**
     * @var string
     */
    public $layout = 'content';

    /**
     * @var QuestionAnswerRepository
     */
    protected $qa;
    /**
     * @var QuestionAnswerCategoryRepository
     */
    protected $categories;


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->qa = new QuestionAnswerRepository();
        $this->categories = new QuestionAnswerCategoryRepository();
    }

    /**
     * @param string $slug
     * @return string
     */
//    public function actionIndex($slug = null)
//    {
//        $dataProvider = $this->qa->search();
//        return $this->render('index', compact('dataProvider', 'slug'));
//    }

    /**
     * @param string $slug
     * @return string
     * @throws NotFoundHttpException
     */
//    public function actionCategory($slug = null)
//    {
//        $category = $this->categories->getBySlugOr404($slug);
//        $dataProvider = $this->qa->search(['qaCategoryId' => $category->id]);
//
//        return $this->render('category', compact('dataProvider', 'slug', 'category'));
//    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $qa = $this->qa->getById($id);
        $this->ensureExists($qa);

        $themes = new ThemeRepository();
        $theme = $themes->byId($qa->themeId);
        $this->ensureExists($theme);

        return $this->redirect(Url::entity($theme), 301);
    }
}

app/views/question-answer/_form-guest.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $model      app\models\QuestionAnswerForm */
/* @var $this       yii\web\View */
/* @var $questionAnswerCategoryMap array*/
?>

<?php $form = ActiveForm::begin([
    'id' => 'qa-form',
    'options' => ['autocomplete' => 'off'],
    'fieldConfig' => [
        'inputOptions' => [
            'class' => 'form-control input-lg',
        ]
    ],
]) ?>

    <div id="snapshot-widget"></div>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'question')->textarea() ?>
    <?= $form->field($model, 'email')->textInput() ?>
    <?= $form->field($model, 'qaCategoryId')->dropDownList($questionAnswerCategoryMap) ?>
    <?= $form->field($model, 'firstName')->textInput() ?>
    <?= $form->field($model, 'isMailNotification')->checkbox() ?>

    <br>

    <button type="submit" class="btn btn-lg btn-primary">Опубликовать вопрос</button>

<?php $form->end() ?>

app/views/question-answer/_form.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $model      app\models\QuestionAnswerForm */
/* @var $this       yii\web\View */
/* @var $questionAnswerCategoryMap array*/

$this->registerJsFile('@web/js/frontend-qa-photos.js', [
    'depends' => [
        'app\assets\AppAsset',
        'app\assets\FileApiAsset',
    ],
]);
?>

<?php $form = ActiveForm::begin([
    'id' => 'qa-form',
    'options' => ['autocomplete' => 'off'],
    'fieldConfig' => [
        'inputOptions' => [
            'class' => 'form-control input-lg',
        ]
    ],
]) ?>

    <div id="snapshot-widget"></div>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'question')->textarea() ?>
    <?= $form->field($model, 'qaCategoryId')->dropDownList($questionAnswerCategoryMap) ?>
    <?= $form->field($model, 'isMailNotification')->checkbox() ?>

    <div class="form-group field-boastform-photos">
        <?= Html::activeLabel($model, 'photos', ['class' => 'control-label']) ?>
        <?= Html::hiddenInput(Html::getInputName($model, 'photos')) ?>


        <div class="row js-uploaded-photos">
            <?php foreach ($model->photos as $photoId): ?>
                <?= Html::hiddenInput(Html::getInputName($model, 'photos[]'), $photoId) ?>
            <?php endforeach ?>
        </div>

        <p class="help-block" data-fileapi="active.show" style="display: none">
            <span class="fa fa-spinner fa-spin"></span>
            Идёт загрузка фотографий
        </p>

        <label class="b-upload-btn b-upload-btn_style_link">
            <span class="b-upload-btn__label">Добавить больше фотографий</span>
            <input type="file" name="file" class="b-upload-btn__input" id="<?= Html::getInputId($model, 'photos') ?>" />
        </label>
    </div>
    <br>

    <button type="submit" class="btn btn-lg btn-primary">Опубликовать вопрос</button>

<?php $form->end() ?>

<script type="text/html" id="qa-photo-template">
    <div class="col-xs-6 col-sm-3 col-md-2">
        <a href="#" class="thumbnail b-upload-thumb b-upload-thumb_state_hoverable js-photo-delete" onclick="return false">
            <input type="hidden" name="<?= Html::getInputName($model, 'photos[]') ?>" value="<%= id %>" />
            <span class="b-upload-thumb__image" style="background-image: url(<%= url %>)"></span>

            <span class="b-upload-thumb__hover">
                <span class="b-upload-thumb__hover-inner">
                    <span class="b-upload-thumb__hover-icon fa fa-trash-o"></span>
                    <span class="b-upload-thumb__hover-text">Нажмите, чтобы&nbsp;удалить</span>
                </span>
            </span>
        </a>
    </div>
</script>

app/views/question-answer/_item.php
<?php
use app\helpers\Url;
use yii\helpers\Html;

/* @var $model app\db\records\QuestionAnswer */
/* @var $this  app\components\View */
?>

<div class="b-publication">
    <h3><?= Html::a(Html::encode($model->title), Url::to(['question-answer/view', 'id'=>$model->id, 'slug'=>$model->slug, 'categorySlug'=>$model->qaCategory->slug]), ['class' => 'border-link']) ?></h3>

    <?= Yii::$app->formatter->asHtml($model->getContentPreview()) ?>

    <br/>
    <br/>

    <ul class="b-publication-meta list-unstyled">
        <li>
            <img class="b-meta__icon b-meta__icon_type_avatar" src="<?= Url::avatar($model, ['w' => 50, 'h' => 50]) ?>">
            <?php if($model->userId):?>
                <a target="_blank" href="<?= Url::to(['profile/view', 'id'=>$model->user->id]) ?>"><?= $model->present()->userName() ?></a>
            <?php else:?>
                <?= $model->present()->userName() ?>
            <?php endif;?>
        </li>
        <li>
            <span class="fa fa-fw fa-clock-o"></span>
            <?= $model->present()->timeCreated() ?>
        </li>
        <li>
            <span class="fa fa-fw fa-bookmark"></span>
            <a href="<?= Url::to(['question-answer/category', 'slug'=>$model->qaCategory->slug]) ?>"><?= Html::encode($model->qaCategory->name) ?></a>
        </li>
        <li>
            <span class="fa fa-fw fa-comment-o"></span>
            <a href="<?= Url::to(['question-answer/view', 'id'=>$model->id, 'slug'=>$model->slug, 'categorySlug'=>$model->qaCategory->slug]) ?>">
                <?= $model->present()->commentCount() ?>
            </a>
        </li>
    </ul>
</div>

app/views/question-answer/category.php
<?php
use app\widgets\QuestionAnswerListView;
use yii\helpers\Html;

/* @var $dataProvider yii\data\BaseDataProvider */
/* @var $this         yii\web\View */

$this->title = 'Вопрос-Ответ AliExpress';

$this->title = $category->seoTitle ?: $category->name;
$this->params['breadcrumbs'][] = ['label' => 'Вопрос-Ответ', 'url' => ['index']];

$this->params['showQaCategoriesBlock'] = true;
?>

<?php $this->beginContent('@app/views/layouts/_sidebar.php') ?>

    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>

<?= QuestionAnswerListView::widget([
    'dataProvider' => $dataProvider,
    'viewParams' => compact('slug')
]) ?>

<?php $this->endContent() ?>

app/views/question-answer/create.php
<?php
use yii\helpers\Html;

/* @var $model      app\models\QuestionAnswerForm */
/* @var $this       yii\web\View */
/* @var $isGuest */

$this->title = 'Новый вопрос';
?>

<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?= $this->render($isGuest ? '_form-guest' : '_form', compact('model', 'questionAnswerCategoryMap')) ?>

app/views/question-answer/index.php
<?php
use app\widgets\QuestionAnswerListView;
use yii\helpers\Html;

/* @var $dataProvider yii\data\BaseDataProvider */
/* @var $this         yii\web\View */

$this->title = 'Вопрос-Ответ AliExpress';
$this->registerMetaTag(['name' => 'description', 'content' => 'Вам нужна помощь по Алиэкспресс? Задавайте свои вопросы и получайте оперативные ответы на тему Алиэкспресс.']);
$this->params['showQaCategoriesBlock'] = true;
?>

<?php $this->beginContent('@app/views/layouts/_sidebar.php') ?>

    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>

<?= QuestionAnswerListView::widget([
    'dataProvider' => $dataProvider,
    'viewParams' => compact('slug')
]) ?>

<?php $this->endContent() ?>

app/views/question-answer/view.php
<?php
use app\assets\FotoramaAsset;
use app\helpers\Url;
use app\widgets\Comments;
use yii\helpers\Html;

/* @var $qa app\db\records\QuestionAnswer */
/* @var $this  yii\web\View */

$this->title = $qa->title . ' — вопрос-ответ Алиэкспресс';
$this->registerMetaTag(['name' => 'description', 'content' => 'Ответ на вопрос ' . $qa->title . ' - вопрос-ответ Алиэкспресс']);

$this->params['breadcrumbs'][] = ['label' => 'Вопрос-Ответ', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $qa->qaCategory->name, 'url' => ['category', 'slug' => $qa->qaCategory->slug]];

FotoramaAsset::register($this);
?>

<div class="page-header">
    <h1><?= Html::encode($qa->title) ?></h1>
</div>

<p><?= Yii::$app->formatter->asNtext($qa->question) ?></p>

<div class="b-qa__image-wrapper">
    <?php foreach ($qa->photos as $photo): ?>
        <img class="b-qa__image img-thumbnail" src="<?= Url::thumb($photo, ['w' => 500]) ?>" alt="<?= Html::encode($qa->title) ?>">
    <?php endforeach ?>
</div>

<ul class="b-publication-meta list-unstyled">
    <li>
        <img class="b-meta__icon b-meta__icon_type_avatar" src="<?= Url::avatar($qa->user, ['w' => 50, 'h' => 50]) ?>">
        <?php if($qa->userId):?>
            <a target="_blank" href="<?= Url::to(['profile/view', 'id' => $qa->user->id]) ?>"><?= $qa->present()->userName() ?></a>
        <?php else:?>
            <?= $qa->present()->userName() ?>
        <?php endif;?>
    </li>
    <li>
        <span class="fa fa-fw fa-clock-o"></span>
        <?= $qa->present()->timeCreated() ?>
    </li>
    <li>
        <span class="fa fa-fw fa-bookmark"></span>
        <a href="<?= Url::to(['question-answer/category', 'slug' => $qa->qaCategory->slug]) ?>"><?= Html::encode($qa->qaCategory->name) ?></a>
    </li>
    <li>
        <span class="fa fa-fw fa-comment-o"></span>
        <?= $qa->present()->commentCount() ?>
    </li>
</ul>

<?= Comments::widget([
    'url' => Url::to(['question-answer/comments', 'id' => $qa->id]),
    'template' => '@app/views/comments/qa-templates'
]) ?>