app/modules/forum/models/CommentForm.php
<?php
namespace app\modules\forum\models;

use Yii;
use yii\base\Model;

/**
 * @property string $content
 *
 * @author Mark Moskalenko <office@it-yes.com>
 * @author Artem Belov <razor2909@gmail.com>
 */
class CommentForm extends Model
{
    /**
    * @var string 
    */
    public $content;


    /**
    * @inheritdoc
    */
    public function rules()
    {
        return [
            ['content', 'string'],
            ['content', 'trim', 'enableClientValidation' => false],
            ['content', 'required', 'message' => 'Необходимо укзать текст сообщения.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'content' => 'Комментарий',
        ];
    }
}

app/modules/forum/controllers/CommentsController.php
<?php
namespace app\modules\forum\controllers;

use app\filters\AjaxOnly;
use app\filters\JsonFormatter;
use app\filters\PostOnly;
use app\helpers\Url;
use app\modules\forum\models\CommentForm;
use app\modules\forum\repositories\CommentRepository;
use app\modules\forum\repositories\ThemeRepository;
use Yii;

/**
 * @author Artem Belov <razor2909@gmail.com>
 */
class CommentsController extends BaseController
{
    /**
     * @var ThemeRepository
     */
    protected $themes;
    /**
     * @var CommentRepository
     */
    protected $comments;


    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        $this->themes = new ThemeRepository();
        $this->comments = new CommentRepository();
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            [
                'class' => AjaxOnly::className(),
                'only' => ['create', 'update'],
            ],
            [
                'class' => PostOnly::className(),
                'only' => ['create'],
            ],
            [
                'class' => JsonFormatter::className(),
                'only' => ['create'],
            ]
        ];
    }

    /**
     * @param integer $themeId
     * @return mixed
     */
    public function actionIndex($themeId)
    {
        $theme = $this->themes->byId($themeId);
        $this->ensureExists($theme);

        $dataProvider = $this->comments->search(['themeId' => $theme->id], $theme);
        $fixedComments = $this->comments->findAllFixedByThemeId($theme->id, $theme);

        $commentModel = new CommentForm();

        return $this->render('index', compact('theme', 'dataProvider', 'fixedComments', 'commentModel'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);

        $dataProvider = $this->comments->search(['themeId' => $comment->themeId], $comment->theme);
        $pageParam = $dataProvider->pagination->pageParam;
        $page = $this->comments->calcPage($comment, $dataProvider);

        $route = ['index', 'themeId' => $comment->themeId, '#' => 'c' . $comment->id];
        if ($page) {
            $route[ $pageParam ] = $page;
        }

        $this->redirect($route, 301);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionRaw($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);

        return $comment->content;
    }

    /**
     * @param integer $themeId
     * @return mixed
     */
    public function actionCreate($themeId)
    {
        $theme = $this->themes->byId($themeId);
        $this->ensureExists($theme);
        $this->ensureAllowed('createForumComment', ['theme' => $theme]);

        $model = new CommentForm();
        $model->load(Yii::$app->request->post());

        if ($model->validate()) {
            $comment = $this->comments->create(['themeId' => $theme->id, 'content' => $model->content]);

            $dataProvider = $this->comments->search(['themeId' => $theme->id], $theme);

            $page = $this->comments->calcPage($comment, $dataProvider);
            $html = $this->renderPartial('_item', ['model' => $comment]);
            $url = Url::entity($comment);

            return compact('html', 'page', 'url');
        }

        Yii::$app->response->statusCode = 400;
        return ['message' => $model->getFirstError('content')];
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('updateForumComment', ['comment' => $comment]);

        $model = new CommentForm(['content' => $comment->content]);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $this->comments->replicate($comment, Yii::$app->user->id);
                $this->comments->update($comment, ['content' => $model->content]);
                return $this->renderPartial('_item', ['model' => $comment]);
            } else {
                Yii::$app->response->statusCode = 400;
                return $model->getFirstError('content');
            }
        }

        return $this->renderPartial('_form-update', compact('comment', 'model'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('deleteForumComment', ['comment' => $comment]);

        if ($comment->isInitial) {
            $redirectUrl = Url::entity($comment->theme->board);
        } else {
            $redirectUrl = Url::entity($comment->theme);
        }

        $this->comments->delete($comment);

        return $this->redirect($redirectUrl);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionHide($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('hideForumComment', ['comment' => $comment]);

        $this->comments->hide($comment);

        return $this->redirect(Url::entity($comment->theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionShow($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('hideForumComment', ['comment' => $comment]);

        $this->comments->show($comment);

        return $this->redirect(Url::entity($comment->theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionPin($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('pinForumComment', ['comment' => $comment]);

        $this->comments->pin($comment);

        return $this->redirect(Url::entity($comment->theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUnpin($id)
    {
        $comment = $this->comments->byId($id);
        $this->ensureExists($comment);
        $this->ensureAllowed('pinForumComment', ['comment' => $comment]);

        $this->comments->unpin($comment);

        return $this->redirect(Url::entity($comment->theme));
    }
}

app/modules/forum/controllers/DefaultController.php
<?php
namespace app\modules\forum\controllers;

use app\filters\JsonFormatter;
use app\helpers\Url;
use app\models\ImageUploadForm;
use app\modules\forum\repositories\CategoryRepository;
use app\modules\forum\repositories\ImageRepository;
use Yii;
use yii\web\UploadedFile;

/**
 * @author Artem Belov <razor2909@gmail.com>
 */
class DefaultController extends BaseController
{
    /**
     * @var CategoryRepository
     */
    protected $categories;
    /**
     * @var ImageRepository
     */
    protected $images;


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => JsonFormatter::className(),
                'only' => ['upload-image'],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        $this->categories = new CategoryRepository();
        $this->images = new ImageRepository();
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $categories = $this->categories->all();
        return $this->render('index', compact('categories'));
    }

    /**
     * @return array
     */
    public function actionUploadImage()
    {
        $form = new ImageUploadForm();
        $form->file = UploadedFile::getInstanceByName('file');

        if ($form->validate()) {
            $image = $this->images->create($form->file);
            return ['id' => $image->id, 'url' => Url::uploaded($image)];
        }

        Yii::$app->response->statusCode = 400;
        return ['message' => $form->getFirstError('file')];
    }
}

app/modules/forum/controllers/ThemesController.php
<?php
namespace app\modules\forum\controllers;

use app\db\records\Seller;
use app\filters\LoginRequired;
use app\helpers\Url;
use app\modules\forum\models\MoveThemeForm;
use app\modules\forum\models\ThemeForm;
use app\modules\forum\repositories\BoardRepository;
use app\modules\forum\repositories\CommentRepository;
use app\modules\forum\repositories\ThemeRepository;
use Yii;

/**
 * @author Artem Belov <razor2909@gmail.com>
 */
class ThemesController extends BaseController
{
    /**
     * @var BoardRepository
     */
    protected $boards;
    /**
     * @var ThemeRepository
     */
    protected $themes;
    /**
     * @var CommentRepository
     */
    protected $comments;


    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        $this->boards = new BoardRepository();
        $this->themes = new ThemeRepository();
        $this->comments = new CommentRepository();
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => LoginRequired::className(),
                'only' => ['create', 'update', 'delete'],
            ],
        ];
    }

    /**
     * @param integer $boardId
     * @return string
     */
    public function actionIndex($boardId)
    {
        $board = $this->boards->getById($boardId);
        $this->ensureExists($board);

        $dataProvider = $this->themes->search(['boardId' => $board->id], $board->hideEmpty);
        $fixedThemes = $this->themes->findAllFixedByTopicId($board->id);

        return $this->render('index', compact('board', 'dataProvider', 'fixedThemes'));
    }

    /**
     * @param integer $boardId
     * @return mixed
     */
    public function actionCreate($boardId)
    {
        $board = $this->boards->getById($boardId);
        $this->ensureExists($board);
        $this->ensureAllowed('createForumTheme', ['board' => $board]);

        $model = new ThemeForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $theme = $this->themes->create(['boardId' => $board->id, 'title' => $model->title]);
            $this->comments->create(['themeId' => $theme->id, 'content' => $model->comment], $initial = true);
            return $this->redirect(Url::entity($theme));
        }

        return $this->render('create', compact('board', 'model'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('updateForumTheme', ['theme' => $theme]);

        $comment = $this->comments->getInitial($theme->id);

        $model = new ThemeForm();
        $model->setScenario(ThemeForm::SCENARIO_UPDATE);
        $model->title = $theme->title;
        if ($comment) {
            $model->comment = $comment->content;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $this->themes->update($theme, $model->attributes);

            if ($comment) {
                $this->comments->update($comment, ['content' => $model->comment]);
            }

            return $this->redirect(Url::entity($theme));
        }

        return $this->render('update', compact('theme', 'model'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('deleteForumTheme', ['theme' => $theme]);

        $boardUrl = Url::entity($theme->board);
        $theme->delete();

        return $this->redirect($boardUrl);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionMove($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('moveForumTheme', ['theme' => $theme]);

        $model = new MoveThemeForm(['boardId' => $theme->boardId]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $this->themes->move($theme, $model->boardId);
            return $this->redirect(Url::entity($theme));
        }

        $boardMap = $this->boards->getMap();

        return $this->render('move', compact('theme', 'model', 'boardMap'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionClose($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('closeForumTheme', ['theme' => $theme]);

        $this->themes->close($theme);

        return $this->redirect(Url::entity($theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionOpen($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('closeForumTheme', ['theme' => $theme]);

        $this->themes->open($theme);

        return $this->redirect(Url::entity($theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionPin($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('pinForumTheme', ['theme' => $theme]);

        $this->themes->pin($theme);

        return $this->redirect(Url::entity($theme));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUnpin($id)
    {
        $theme = $this->themes->byId($id);
        $this->ensureExists($theme);
        $this->ensureAllowed('pinForumTheme', ['theme' => $theme]);

        $this->themes->unpin($theme);

        return $this->redirect(Url::entity($theme));
    }

    /**
     * @param integer $id
     * @return \yii\web\Response
     */
    public function actionSeller($id)
    {
        /* @var $seller Seller */
        $seller = Seller::findOne($id);
        $this->ensureExists($seller);

        $theme = $this->themes->getBySellerId($seller->id);

        if ( ! $theme) {
            $theme = $this->themes->createForSeller($seller);
        }

        return $this->redirect(Url::entity($theme), 301);
    }
}

app/modules/forum/views/comments/_form-create.php
<?php
use app\assets\AutosizeAsset;
use app\assets\ImagesUploaderAsset;
use app\helpers\Angular;
use app\helpers\Url;
use yii\bootstrap\ActiveForm;

/* @var $theme       app\modules\forum\entities\Theme */
/* @var $model       app\modules\forum\models\CommentForm */
/* @var $this        yii\web\View */

ImagesUploaderAsset::register($this);
AutosizeAsset::register($this);
?>

<br>

<?php $form = ActiveForm::begin([
    'id' => 'comment-form-create',
    'action' => ['create', 'themeId' => $theme->id],
    'options' => ['autocomplete' => 'off'],
    'validateOnChange' => false,
    'validateOnBlur' => false,
]) ?>

    <?= $form->field($model, 'content', [
        'template' => "{input}\n{hint}\n{error}\n{images}",
        'parts' => [
            '{images}' => Angular::directive('images-uploader', [
                'upload-url' => Url::to(['default/upload-image']),
                'template' => '#images-uploader-redactor-template'
            ]),
        ],
    ])->widget('app\widgets\Redactor', [
        'options' => ['class' => 'autosize', 'rows' => 3],
    ]) ?>

    <button type="button" class="btn btn-lg btn-primary" onclick="saveCreatedComment()">Добавить сообщение</button>
<?php $form->end() ?>

app/modules/forum/views/comments/_form-update.php
<?php
use app\helpers\Angular;
use app\helpers\Url;
use yii\bootstrap\ActiveForm;

/* @var $comment app\modules\forum\entities\Comment */
/* @var $model   app\modules\forum\models\CommentForm */
/* @var $this    yii\web\View */

$author = $comment->user;
?>

<?php $form = ActiveForm::begin([
    'id' => 'comment-form-update',
    'action' => ['update', 'id' => $comment->id],
    'options' => ['class' => 'forum-comment-list__item', 'autocomplete' => 'off'],
    'validateOnChange' => false,
    'validateOnBlur' => false,
]) ?>

<div class="forum-comment-list__item-profile">
    <div class="forum-profile">
        <div class="forum-profile__username">
            <a href="#" onclick="referUser(this); return false;"><?= $author->name ?></a>
        </div>

        <div class="forum-profile__avatar">
            <a href="<?= Url::entity($author) ?>">
                <img class="img-responsive" src="<?= Url::avatar($author, ['w' => 100, 'h' => 100]) ?>" alt="<?= $author->name ?>"/>
            </a>
        </div>

        <div class="forum-profile__comments">
            <div class="fa fa-fw fa-comment-o"></div>
            <?= $author->present()->forumCommentCount() ?>
        </div>
    </div>
</div>

<div class="forum-comment-list__item-body">
    <?= $form->field($model, 'content', [
        'template' => "{input}\n{hint}\n{error}\n{images}",
        'parts' => [
            '{images}' => Angular::directive('images-uploader', [
                'upload-url' => Url::to(['default/upload-image']),
                'template' => '#images-uploader-redactor-template',
            ]),
        ],
    ])->widget('app\widgets\Redactor', [
        'options' => ['class' => 'autosize', 'rows' => 3],
    ]) ?>
</div>

<div class="clearfix"></div>

<div class="forum-comment-list__item-footer">
    <button type="button" class="btn btn-primary" onclick="saveUpdatedComment()">Сохранить сообщение</button>
    или
    <a class="border-link border-link-dashed" href="#" onclick="cancelUpdate(); return false;">отменить</a>
</div>

<?php $form->end() ?>

app/modules/forum/views/comments/_item.php
<?php
use app\modules\forum\helpers\BBCodeParser;
use app\modules\forum\helpers\HtmlPurifier;
use app\helpers\Url;

/* @var $model app\modules\forum\entities\Comment */
/* @var $this  yii\web\View */

$comment = $model;
$author = $comment->user;
?>

<div class="forum-comment-list__item" data-key="<?= $comment->id ?>">
    <div id="c<?= $comment->id ?>" class="anchor"></div>

    <div class="forum-comment-list__item-profile">
        <div class="forum-profile">
            <div class="forum-profile__username">
                <a href="#" title="Ответить" onclick="referUser(this); return false;"><?= $author->name ?></a>
            </div>

            <div class="forum-profile__avatar">
                <a href="<?= Url::entity($author) ?>">
                    <img class="img-responsive" src="<?= Url::avatar($author, ['w' => 100, 'h' => 100]) ?>" alt="<?= $author->name ?>"/>
                </a>
            </div>

            <div class="forum-profile__comments">
                <div class="fa fa-fw fa-comment-o"></div>
                <?= $author->present()->forumCommentCount() ?>
            </div>
        </div>
    </div>

    <div class="forum-comment-list__item-body">
        <div class="forum-comment">
            <div class="col-xs-10">
                <ul class="forum-comment__meta">
                    <li>
                        <a href="#c<?= $comment->id ?>" class="link-muted">#</a>
                    </li>

                    <li>
                        <?= $comment->present()->timeCreated() ?>
                    </li>
                </ul>

                <div class="forum-comment__content">
                    <?= BBCodeParser::process($comment->content) ?>
                </div>
            </div>

            <div class="col-xs-2">
                <div class="forum-comment__actions">
                    <?php if (Yii::$app->user->can('updateForumComment', ['comment' => $comment])): ?>
                        <a href="#" onclick="updateComment(this); return false;">Редактировать</a>
                    <?php endif ?>

                    <?php if (Yii::$app->user->can('deleteForumComment', ['comment' => $comment])): ?>
                        <a href="<?= Url::to(['delete', 'id' => $comment->id]) ?>" data-method="post">Удалить</a>
                    <?php endif ?>

                    <?php if (Yii::$app->user->can('pinForumComment', ['comment' => $comment])): ?>
                        <?php if ($comment->isFixed): ?>
                            <a href="<?= Url::to(['unpin', 'id' => $comment->id]) ?>">Открепить</a>
                        <?php else: ?>
                            <a href="<?= Url::to(['pin', 'id' => $comment->id]) ?>">Прикрепить</a>
                        <?php endif ?>
                    <?php endif ?>

                    <?php if (Yii::$app->user->can('hideForumComment', ['comment' => $comment])): ?>
                        <?php if ($comment->isHidden): ?>
                            <a href="<?= Url::to(['show', 'id' => $comment->id]) ?>">Показать</a>
                        <?php else: ?>
                            <a href="<?= Url::to(['hide', 'id' => $comment->id]) ?>">Скрыть</a>
                        <?php endif ?>
                    <?php endif ?>

                    <?php if ( ! Yii::$app->user->isGuest): ?>
                        <a href="#" onclick="quoteComment(this); return false;">Цитировать</a>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
</div>

app/modules/forum/views/comments/_layout.php
<?php
use app\helpers\Url;

/* @var $theme app\modules\forum\entities\Theme */
/* @var $this  yii\web\View */
?>

<div class="forum-panel">
    <?php if ($theme->isClosed): ?>
        <span class="forum-panel__control btn btn-inverse" style="position: absolute; top: 0; left: 0">
            <span class="fa fa-lock"></span>
            Тема закрыта
        </span>
    <?php elseif (Yii::$app->user->can('createForumComment', ['theme' => $theme])): ?>
        <div style="position: absolute; top: 0; left: 0">
            <a href="#comment-form-create" class="forum-panel__control btn btn-inverse">Новое сообщение</a>
        </div>
    <?php endif ?>

    {pager}

    <?php if (Yii::$app->user->can('moderateForumTheme', ['theme' => $theme])): ?>
        <div class="dropdown" style="position: absolute; top: 0; right: 0">
            <button class="forum-panel__control btn btn-inverse dropdown-toggle" type="button" data-toggle="dropdown">
                Действия над темой
                <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
                <?php if (Yii::$app->user->can('updateForumTheme', ['theme' => $theme])): ?>
                    <li><a href="<?= Url::to(['themes/update', 'id' => $theme->id]) ?>">Переименовать тему</a></li>
                <?php endif ?>

                <?php if (Yii::$app->user->can('moveForumTheme', ['theme' => $theme])): ?>
                    <li><a href="<?= Url::to(['themes/move', 'id' => $theme->id]) ?>">Переместить тему</a></li>
                <?php endif ?>

                <?php if (Yii::$app->user->can('pinForumTheme', ['theme' => $theme])): ?>
                    <?php if ($theme->isFixed): ?>
                        <li><a href="<?= Url::to(['themes/unpin', 'id' => $theme->id]) ?>">Открепить тему</a></li>
                    <?php else: ?>
                        <li><a href="<?= Url::to(['themes/pin', 'id' => $theme->id]) ?>">Прикрепить тему</a></li>
                    <?php endif ?>
                <?php endif ?>

                <?php if (Yii::$app->user->can('closeForumTheme', ['theme' => $theme])): ?>
                    <?php if ($theme->isClosed): ?>
                        <li><a href="<?= Url::to(['themes/open', 'id' => $theme->id]) ?>">Открыть тему</a></li>
                    <?php else: ?>
                        <li><a href="<?= Url::to(['themes/close', 'id' => $theme->id]) ?>">Закрыть тему</a></li>
                    <?php endif ?>
                <?php endif ?>
            </ul>
        </div>
    <?php endif ?>
</div>

<div class="forum-comment-list">
    {items}
</div>

<div class="forum-panel">
    <?php if ($theme->isClosed): ?>
        <span class="forum-panel__control btn btn-inverse" style="position: absolute; top: 0; left: 0">
            <span class="fa fa-lock"></span>
            Тема закрыта
        </span>
    <?php endif ?>

    {pager}

    <?php if (Yii::$app->user->can('moderateForumTheme', ['theme' => $theme])): ?>
        <div class="dropdown" style="position: absolute; top: 0; right: 0">
            <button class="forum-panel__control btn btn-inverse dropdown-toggle" type="button" data-toggle="dropdown">
                Действия над темой
                <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
                <?php if (Yii::$app->user->can('updateForumTheme', ['theme' => $theme])): ?>
                    <li><a href="<?= Url::to(['themes/update', 'id' => $theme->id]) ?>">Переименовать тему</a></li>
                <?php endif ?>

                <?php if (Yii::$app->user->can('moveForumTheme', ['theme' => $theme])): ?>
                    <li><a href="<?= Url::to(['themes/move', 'id' => $theme->id]) ?>">Переместить тему</a></li>
                <?php endif ?>

                <?php if (Yii::$app->user->can('pinForumTheme', ['theme' => $theme])): ?>
                    <?php if ($theme->isFixed): ?>
                        <li><a href="<?= Url::to(['themes/unpin', 'id' => $theme->id]) ?>">Открепить тему</a></li>
                    <?php else: ?>
                        <li><a href="<?= Url::to(['themes/pin', 'id' => $theme->id]) ?>">Прикрепить тему</a></li>
                    <?php endif ?>
                <?php endif ?>

                <?php if (Yii::$app->user->can('closeForumTheme', ['theme' => $theme])): ?>
                    <?php if ($theme->isClosed): ?>
                        <li><a href="<?= Url::to(['themes/open', 'id' => $theme->id]) ?>">Открыть тему</a></li>
                    <?php else: ?>
                        <li><a href="<?= Url::to(['themes/close', 'id' => $theme->id]) ?>">Закрыть тему</a></li>
                    <?php endif ?>
                <?php endif ?>
            </ul>
        </div>
    <?php endif ?>
</div>

app/modules/forum/views/comments/index.php
<?php
use app\helpers\Url;
use app\modules\forum\assets\ForumAsset;
use app\modules\forum\widgets\CommentList;
use yii\helpers\Html;

/* @var $theme         app\modules\forum\entities\Theme */
/* @var $fixedComments app\modules\forum\entities\Comment[] */
/* @var $commentModel  app\modules\forum\models\CommentForm */
/* @var $dataProvider  yii\data\DataProviderInterface */
/* @var $this          yii\web\View */

$this->params['breadcrumbs'][] = ['label' => 'Форум Алиэкспресс', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => $theme->board->title, 'url' => Url::entity($theme->board)];
$this->title = $theme->title . ' - форум Алиэкспресс';

ForumAsset::register($this);
?>

<div class="page-header">
    <h1><?= Html::encode($theme->title) ?></h1>
</div>

<?= CommentList::widget([
    'dataProvider' => $dataProvider,
    'fixedComments' => $fixedComments,
    'theme' => $theme,
]) ?>

<?php if ( ! Yii::$app->user->isGuest && ! $theme->isClosed) :?>
    <?= $this->render('_form-create', ['theme' => $theme, 'model' => $commentModel, 'isNewRecord' => true]) ?>
<?php endif ?>

<?php if (Yii::$app->user->isGuest): ?>
    <div class="forum-register-required">
        <a href="<?= Url::to(['@signup']) ?>">Зарегистрируйтесь</a> или <a href="<?= Url::to(['@login']) ?>">войдите</a> на сайт,
        чтобы начать общение на форуме.
    </div>
<?php endif ?>

<div class="clearfix"></div>